baseURL = 'https://prescott.strangled.net/'
languageCode = 'en-us'
title = 'My Homepage'
theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/nickwales/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/nickwales/"}
  ]